<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="./employee.css" ?>
<!DOCTYPE employees [
  <!ELEMENT employees (employee*)>
  <!ELEMENT employee (name, phones, addresses, email)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT phones (phone+)>
  <!ELEMENT phone (#PCDATA)>
  <!ATTLIST phone
    Type (home|work|mobile) #REQUIRED>
  <!ELEMENT addresses (address+)>
  <!ELEMENT address (Street, BuildingNumber, Number, Region, City, Country)>
  <!ELEMENT Street (#PCDATA)>
  <!ELEMENT BuildingNumber (#PCDATA)>
  <!ELEMENT Number (#PCDATA)>
  <!ELEMENT Region (#PCDATA)>
  <!ELEMENT City (#PCDATA)>
  <!ELEMENT Country (#PCDATA)>
  <!ELEMENT email (#PCDATA)>
]>

<employees>
    <employee>
        <name>Mohamed Torkey</name>
        <phones>
            <phone Type="home">555-4323-4567</phone>
            <phone Type="work">555-987-6543</phone>
            <phone Type="mobile">555-555-5555</phone>
        </phones>
        <addresses>
            <address>
                <Street>Main Street</Street>
                <BuildingNumber>Building 10</BuildingNumber>
                <Number>123</Number>
                <Region>East</Region>
                <City>Cityville</City>
                <Country>USA</Country>
            </address>
        </addresses>
        <email>mohamed.torkey@23.com</email>
    </employee>
   
    <employee>
        <name>Alice Johnson</name>
        <phones>
            <phone Type="work">555-111-2222</phone>
            <phone Type="mobile">555-333-4444</phone>
            <phone Type="mobile">555-555-5555</phone>
        </phones>
        <addresses>
            <address>
                <Street>First Avenue</Street>
                <BuildingNumber>Building 20</BuildingNumber>
                <Number>456</Number>
                <Region>West</Region>
                <City>Townsville</City>
                <Country>Canada</Country>
            </address>
        </addresses>
        <email>alice.johnson@32.com</email>
    </employee>
    
    <employee>
        <name>John Doe</name>
        <phones>
            <phone Type="home">555-111-2222</phone>
            <phone Type="work">555-333-4444</phone>
            <phone Type="mobile">555-555-5555</phone>
        </phones>
        <addresses>
            <address>
                <Street>Main Street</Street>
                <BuildingNumber>Building 20</BuildingNumber>
                <Number>456</Number>
                <Region>West</Region>
                <City>Citytown</City>
                <Country>USA</Country>
            </address>
        </addresses>
        <email>john.doe@32.com</email>
    </employee>    
</employees>
